export enum ActionType {
	FETCH_TICKET = 'FETCH_TICKET',
	CREATE_TICKET = 'CREATE_TICKET',
	REGISTER_SUCCESS = 'REGISTER_SUCCESS',
	REGISTER_FAIL = 'REGISTER_FAIL',
	LOGIN_SUCCESS = 'LOGIN_SUCCESS',
	LOGIN_FAIL = 'LOGIN_FAIL',
	LOGOUT = 'LOGOUT',
	SET_MESSAGE = 'SET_MESSAGE',
	CLEAR_MESSAGE = 'CLEAR_MESSAGE',
	FETCH_PEOPLE = 'FETCH_PEOPLE',
	CREATE_CHECKIN = 'CREATE_CHECKIN',
	FETCH_CHECKIN = 'FETCH_CHECKIN',
}
